# WordPress Test Matrix for Plugin
# https://github.com/thingsym/wordpress-test-matrix

os: linux
dist: xenial

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.4 WP_MULTISITE=0
  - WP_VERSION=5.3 WP_MULTISITE=0
  - WP_VERSION=5.2 WP_MULTISITE=0
  - WP_VERSION=5.1 WP_MULTISITE=0
  - WP_VERSION=5.0 WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=3.7 WP_MULTISITE=0

jobs:
  fast_finish: true
  include:
    # PHP 5.4(.x) - 5.5(.x) support is available on Precise and Trusty only
    # https://docs.travis-ci.com/user/languages/php/
    - php: 5.5
      dist: trusty
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=5.4 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=5.1 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=5.0 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.3 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.5
      dist: trusty
      env: WP_VERSION=3.7 WP_MULTISITE=0

    - php: 5.4
      dist: trusty
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=5.4 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=5.1 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=5.0 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.3 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.4
      dist: trusty
      env: WP_VERSION=3.7 WP_MULTISITE=0

    # PHP 5.2(.x) - 5.3(.x) support is available on Precise only
    - php: 5.3
      dist: precise
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=5.4 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=5.1 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=5.0 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.3 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=3.7 WP_MULTISITE=0
  allow_failures:
    # php version > 7.0 - PasswordHash has a deprecated constructor
    # WP_VERSION from 3.9 to 4.2
    - php: 7.4
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 7.4
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.4
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.4
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=3.9 WP_MULTISITE=0

    # php varsion 7.0 or later - PHP Fatal error: Uncaught Error: Call to undefined function mysql_connect()
    # php varsion 5.6 or after - WordPress database error Unknown system variable 'storage_engine' for query SET storage_engine = INNODB
    - env: WP_VERSION=3.8 WP_MULTISITE=0
    - env: WP_VERSION=3.7 WP_MULTISITE=0
  exclude:
    # no support WP_VERSION 5.2 or later
    # End official support for PHP5.2 -> 5.5
    # https://core.trac.wordpress.org/changeset/44950
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=5.4 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=5.4 WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: 5.4
      env: WP_VERSION=nightly WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=5.4 WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=5.3 WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=nightly WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # for WP_VERSION < 4.6 due to PHP Fatal error: Class 'PHPUnit_Framework_TestCase' not found
  # for WP_VERSION < 5.0 due to Fatal error: Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test)
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]] && [[ "$WP_VERSION" < 4.6* ]] ; then
      composer global require "phpunit/phpunit=5.7.*"
    elif [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]] && [[ "$WP_VERSION" < 5.0* ]]  ; then
      composer global require "phpunit/phpunit=6.*"
    else
      composer global require "phpunit/phpunit=4.8.*|5.4.*|6.*|7.*"
    fi
  # disable WP_DEBUG for PHP >= 5.5 due to ext/mysqli E_DEPRECATED errors
  - |
    if [[ "$TRAVIS_PHP_VERSION" > 5.4* ]] && [[ "$WP_VERSION" == "3.6" ]] ; then
      sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" /tmp/wordpress-tests-lib/wp-tests-config.php;
    fi
  - |
    if [[ "$TRAVIS_PHP_VERSION" > 5.4* ]] && [[ "$WP_VERSION" == "3.7" ]] ; then
      sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" /tmp/wordpress-tests-lib/wp-tests-config.php;
    fi
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

script:
  - phpunit
